
version: 2.1

orbs:
  cypress: cypress-io/cypress@1.27.0

workflows:
  version: 2
  pipeline:
    jobs:
      - install:
          filters:
            branches:
              only: main
      - run_tests:
          filters:
            branches:
              only: main
          requires:
            - install
      - cypress/run:
          yarn: true
          install-command: 'echo "Using install from cache"'
          cache-key: v1-dependencies-{{ checksum "package.json" }}
          executor: cypress/base-14
          start: yarn serve
          wait-on: 'http://localhost:5000'
          filters:
            branches:
              only: main
          requires:
            - install
      - publish_github_page:
          filters:
            branches:
              only: main
          requires:
            - run_tests
            - cypress/run

jobs:
  install:
    working_directory: ~/saljuama.github.io
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install && yarn build
      - save_cache:
          paths:
            - node_modules
            - build
          key: v1-dependencies-{{ checksum "package.json" }}

  run_tests:
    working_directory: ~/saljuama.github.io
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn test

  publish_github_page:
    working_directory: ~/saljuama.github.io
    docker:
      - image: circleci/node:14.15.1
    steps:
      - setup_github_write_access
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn deploy

commands:
  setup_github_write_access:
    description: "Setup Github write access"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "08:05:c7:18:e2:e6:83:8e:f6:26:37:b9:3b:f3:e4:8b"
      - run: git config --global user.email "circleci@saljuama.dev"
      - run: git config --global user.name "saljuama (Circle CI)"
