name: Restore Cache 💨
description: Add NodeJS 14.x and restore node modules and cypress binary
runs:
  using: composite
  steps:
    - name: Setup NodeJS 🏃‍
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Restore cache
      uses: actions/cache@v2
      id: yarn-build-cache
      with:
        path: |
          node_modules
          ~/.cache/Cypress
          build
        key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-
