name: deploy-pipeline
on:
  push:
    branches:
      - main

jobs:

  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 💻
        uses: actions/checkout@v2
      - name: Setup NodeJS 🏃‍
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Restore cache 💨
        uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
      - name: Dependencies 📦
        run: yarn install

  unit-tests:
    needs: update-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 💻
        uses: actions/checkout@v2
      - name: Setup NodeJS 🏃‍
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Restore cache 💨
        uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
      - name: Run Tests 🧪
        run: yarn test

  functional-tests:
    needs: update-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 💻
        uses: actions/checkout@v2
      - name: Setup NodeJS 🏃‍
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Restore cache 💨
        uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
      - name: Run Tests 🧪
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000

  deploy-page:
    needs: [unit-tests, functional-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 💻
        uses: actions/checkout@v2
      - name: Setup NodeJS 🏃‍
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Restore cache 💨
        uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
      - name: Build 🔧
        run: yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
